// Generated by gencpp from file wizzybug_msgs/ttc.msg
// DO NOT EDIT!


#ifndef WIZZYBUG_MSGS_MESSAGE_TTC_H
#define WIZZYBUG_MSGS_MESSAGE_TTC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wizzybug_msgs
{
template <class ContainerAllocator>
struct ttc_
{
  typedef ttc_<ContainerAllocator> Type;

  ttc_()
    : header()
    , ttc(0.0)
    , ttc_azimuth(0.0)  {
    }
  ttc_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ttc(0.0)
    , ttc_azimuth(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _ttc_type;
  _ttc_type ttc;

   typedef float _ttc_azimuth_type;
  _ttc_azimuth_type ttc_azimuth;





  typedef boost::shared_ptr< ::wizzybug_msgs::ttc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wizzybug_msgs::ttc_<ContainerAllocator> const> ConstPtr;

}; // struct ttc_

typedef ::wizzybug_msgs::ttc_<std::allocator<void> > ttc;

typedef boost::shared_ptr< ::wizzybug_msgs::ttc > ttcPtr;
typedef boost::shared_ptr< ::wizzybug_msgs::ttc const> ttcConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wizzybug_msgs::ttc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wizzybug_msgs::ttc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wizzybug_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'wizzybug_msgs': ['/home/wizzy-aux/wizzy_git/raspberry_ws/src/wizzybug_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wizzybug_msgs::ttc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wizzybug_msgs::ttc_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wizzybug_msgs::ttc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wizzybug_msgs::ttc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wizzybug_msgs::ttc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wizzybug_msgs::ttc_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wizzybug_msgs::ttc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fd9fba655aceff04f987cabc9046972";
  }

  static const char* value(const ::wizzybug_msgs::ttc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fd9fba655aceff0ULL;
  static const uint64_t static_value2 = 0x4f987cabc9046972ULL;
};

template<class ContainerAllocator>
struct DataType< ::wizzybug_msgs::ttc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wizzybug_msgs/ttc";
  }

  static const char* value(const ::wizzybug_msgs::ttc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wizzybug_msgs::ttc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float32 ttc\n"
"float32 ttc_azimuth\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::wizzybug_msgs::ttc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wizzybug_msgs::ttc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ttc);
      stream.next(m.ttc_azimuth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ttc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wizzybug_msgs::ttc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wizzybug_msgs::ttc_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ttc: ";
    Printer<float>::stream(s, indent + "  ", v.ttc);
    s << indent << "ttc_azimuth: ";
    Printer<float>::stream(s, indent + "  ", v.ttc_azimuth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIZZYBUG_MSGS_MESSAGE_TTC_H
