// Generated by gencpp from file wizzybug_msgs/lidar_data.msg
// DO NOT EDIT!


#ifndef WIZZYBUG_MSGS_MESSAGE_LIDAR_DATA_H
#define WIZZYBUG_MSGS_MESSAGE_LIDAR_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wizzybug_msgs
{
template <class ContainerAllocator>
struct lidar_data_
{
  typedef lidar_data_<ContainerAllocator> Type;

  lidar_data_()
    : header()
    , dist_to_pitfall(0.0)
    , dist_to_obstacle(0.0)
    , dist_to_floor(0.0)  {
    }
  lidar_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dist_to_pitfall(0.0)
    , dist_to_obstacle(0.0)
    , dist_to_floor(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _dist_to_pitfall_type;
  _dist_to_pitfall_type dist_to_pitfall;

   typedef float _dist_to_obstacle_type;
  _dist_to_obstacle_type dist_to_obstacle;

   typedef float _dist_to_floor_type;
  _dist_to_floor_type dist_to_floor;





  typedef boost::shared_ptr< ::wizzybug_msgs::lidar_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wizzybug_msgs::lidar_data_<ContainerAllocator> const> ConstPtr;

}; // struct lidar_data_

typedef ::wizzybug_msgs::lidar_data_<std::allocator<void> > lidar_data;

typedef boost::shared_ptr< ::wizzybug_msgs::lidar_data > lidar_dataPtr;
typedef boost::shared_ptr< ::wizzybug_msgs::lidar_data const> lidar_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wizzybug_msgs::lidar_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wizzybug_msgs::lidar_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wizzybug_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'wizzybug_msgs': ['/home/wizzy-aux/wizzy_git/simulation_ws/src/wizzybug_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wizzybug_msgs::lidar_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wizzybug_msgs::lidar_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wizzybug_msgs::lidar_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wizzybug_msgs::lidar_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wizzybug_msgs::lidar_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wizzybug_msgs::lidar_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wizzybug_msgs::lidar_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c19335d47678d872f794c1f089147d5f";
  }

  static const char* value(const ::wizzybug_msgs::lidar_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc19335d47678d872ULL;
  static const uint64_t static_value2 = 0xf794c1f089147d5fULL;
};

template<class ContainerAllocator>
struct DataType< ::wizzybug_msgs::lidar_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wizzybug_msgs/lidar_data";
  }

  static const char* value(const ::wizzybug_msgs::lidar_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wizzybug_msgs::lidar_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float32 dist_to_pitfall\n"
"float32 dist_to_obstacle\n"
"float32 dist_to_floor\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::wizzybug_msgs::lidar_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wizzybug_msgs::lidar_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dist_to_pitfall);
      stream.next(m.dist_to_obstacle);
      stream.next(m.dist_to_floor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lidar_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wizzybug_msgs::lidar_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wizzybug_msgs::lidar_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dist_to_pitfall: ";
    Printer<float>::stream(s, indent + "  ", v.dist_to_pitfall);
    s << indent << "dist_to_obstacle: ";
    Printer<float>::stream(s, indent + "  ", v.dist_to_obstacle);
    s << indent << "dist_to_floor: ";
    Printer<float>::stream(s, indent + "  ", v.dist_to_floor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIZZYBUG_MSGS_MESSAGE_LIDAR_DATA_H
