// Generated by gencpp from file wizzybug_msgs/obstacleArray.msg
// DO NOT EDIT!


#ifndef WIZZYBUG_MSGS_MESSAGE_OBSTACLEARRAY_H
#define WIZZYBUG_MSGS_MESSAGE_OBSTACLEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <wizzybug_msgs/obstacle.h>

namespace wizzybug_msgs
{
template <class ContainerAllocator>
struct obstacleArray_
{
  typedef obstacleArray_<ContainerAllocator> Type;

  obstacleArray_()
    : header()
    , data()  {
    }
  obstacleArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::wizzybug_msgs::obstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::wizzybug_msgs::obstacle_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> const> ConstPtr;

}; // struct obstacleArray_

typedef ::wizzybug_msgs::obstacleArray_<std::allocator<void> > obstacleArray;

typedef boost::shared_ptr< ::wizzybug_msgs::obstacleArray > obstacleArrayPtr;
typedef boost::shared_ptr< ::wizzybug_msgs::obstacleArray const> obstacleArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wizzybug_msgs::obstacleArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wizzybug_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'wizzybug_msgs': ['/home/tim/wizzy_git/wizzy/simulation_ws/src/wizzybug_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f379a8004de76e2e7e7b8485dc4f074";
  }

  static const char* value(const ::wizzybug_msgs::obstacleArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f379a8004de76e2ULL;
  static const uint64_t static_value2 = 0xe7e7b8485dc4f074ULL;
};

template<class ContainerAllocator>
struct DataType< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wizzybug_msgs/obstacleArray";
  }

  static const char* value(const ::wizzybug_msgs::obstacleArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"wizzybug_msgs/obstacle[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: wizzybug_msgs/obstacle\n"
"std_msgs/Float64 x\n"
"std_msgs/Float64 y\n"
"std_msgs/Float64 z\n"
"std_msgs/Float64 width\n"
"std_msgs/Float64 height\n"
"std_msgs/Float64 length\n"
"\n"
"std_msgs/String classification\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::wizzybug_msgs::obstacleArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obstacleArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wizzybug_msgs::obstacleArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wizzybug_msgs::obstacleArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::wizzybug_msgs::obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIZZYBUG_MSGS_MESSAGE_OBSTACLEARRAY_H
