<?xml version="1.0" ?>
<robot name="wizzybug" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find wizzybug_description)/urdf/common_properties.xacro"/>
    <xacro:include filename="$(find wizzybug_description)/urdf/wizzybug.gazebo"/>

    <xacro:property name="base_length" value="0.4"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.3"/>
    <xacro:property name="base_mass" value="10.0"/>

    <xacro:property name="chair_thickness" value="0.1"/>
    <xacro:property name="chair_width" value="0.3"/>
    <xacro:property name="chair_height" value="0.5"/>
    <xacro:property name="chair_x" value="-0.3"/>
    <xacro:property name="chair_y" value="0.0"/>
    <xacro:property name="chair_z" value="0.2"/>
    <xacro:property name="chair_mass" value="5.0"/>

    <xacro:property name="wheel_radius" value="0.1025"/>
    <xacro:property name="wheel_thickness" value="0.06"/>
    <xacro:property name="wheel_friction" value="0.0"/>
    <xacro:property name="wheel_damping" value="0.1"/>
    <xacro:property name="caster_friction" value="0.0"/>
    <xacro:property name="caster_damping" value="0.0"/>
    <xacro:property name="wheel_mass" value="1.0"/>

    <xacro:property name="caster_wheel_base" value="0.32"/>
    <xacro:property name="caster_axis_x" value="0.45"/>
    <xacro:property name="caster_axis_z" value="0.16"/>
    <xacro:property name="caster_axis_offset_x" value="0.04"/>
    <xacro:property name="caster_axis_offset_z" value="0.16"/>

    <xacro:property name="imu_x" value="0.0"/>
    <xacro:property name="imu_y" value="0.0"/>
    <xacro:property name="imu_z" value="0.0"/>

    <xacro:property name="front_cam_x" value="0.1"/>
    <xacro:property name="front_cam_y" value="0.18"/>
    <xacro:property name="front_cam_z" value="0.16"/>

    <xacro:property name="right_cam_x" value="-0.2"/>
    <xacro:property name="right_cam_y" value="-0.26"/>
    <xacro:property name="right_cam_z" value="0.16"/>

    <xacro:property name="rear_cam_x" value="-0.48"/>
    <xacro:property name="rear_cam_y" value="0.0"/>
    <xacro:property name="rear_cam_z" value="0.63"/>

    <xacro:property name="rplidar_x" value="0.1"/>
    <xacro:property name="rplidar_y" value="0.1"/>
    <xacro:property name="rplidar_z" value="0.0"/>

    <link name="base_footprint">
    </link>
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="${base_length/2} 0.0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>
    <link name="base_link">
        <visual>
            <origin xyz="-0.1 -0.195 -0.05" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wizzybug_description/meshes/Wizzibug_no_wheels.STL"
                      scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="red"/>
        </visual>

        <collision>
            <origin xyz="${-base_length/2} 0.0 ${wheel_radius}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${base_mass}"/>

            <inertia ixx="${1/12*base_mass*(base_width*base_width + base_height*base_height)}" ixy="0.0" ixz="0.0"
                     iyy="${1/12*base_mass*(base_length*base_length + base_height*base_height)}" iyz="0.0"
                     izz="${1/12*base_mass*(base_width*base_width + base_length*base_length)}"/>
        </inertial>
    </link>


    <!-- ################################Left Wheel##############################################-->
    <link name="wheel_left_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.5708 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        </collision>
        <inertial>
            <mass value="${wheel_mass}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="${1/4*wheel_mass*wheel_radius*wheel_radius + 1/12*wheel_mass*wheel_thickness}" ixy="0.0"
                     ixz="0.0"
                     iyy="${1/2*wheel_mass*wheel_radius*wheel_radius}" iyz="0.0"
                     izz="${1/4*wheel_mass*wheel_radius*wheel_radius + 1/12*wheel_mass*wheel_thickness}"/>
        </inertial>
    </link>
    <joint name="wheel_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_left_link"/>
        <origin xyz="0.0 ${base_width/2 + wheel_thickness/2} 0.0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    </joint>

    <!-- ################################Right Wheel##############################################-->
    <link name="wheel_right_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.5708 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <origin rpy="1.5708 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <mass value="${wheel_mass}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="${1/4*wheel_mass*wheel_radius*wheel_radius + 1/12*wheel_mass*wheel_thickness}" ixy="0.0"
                     ixz="0.0"
                     iyy="${1/2*wheel_mass*wheel_radius*wheel_radius}" iyz="0.0"
                     izz="${1/4*wheel_mass*wheel_radius*wheel_radius + 1/12*wheel_mass*wheel_thickness}"/>
        </inertial>
    </link>
    <joint name="wheel_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_right_link"/>
        <origin xyz="0.0 ${-base_width/2 - wheel_thickness/2} 0.0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    </joint>

    <!-- ################################Left caster Wheel##############################################-->

    <link name="left_caster_axle_link">
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0" ixy="0.0"
                     ixz="0.0"
                     iyy="0.0" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <joint name="left_caster_axle_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_caster_axle_link"/>
        <origin xyz="${-caster_axis_x}  ${caster_wheel_base/2+wheel_thickness/2} ${caster_axis_z}" rpy="0 0 0"/>
        <!-- <dynamics damping="${caster_damping}" friction="${caster_friction}"/> -->
    </joint>

    <link name="left_caster_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <origin rpy="1.5708 0 0" xyz="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <origin rpy="1.5708 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <mass value="${wheel_mass}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="${1/4*wheel_mass*wheel_radius*wheel_radius + 1/12*wheel_mass*wheel_thickness}" ixy="0.0"
                     ixz="0.0"
                     iyy="${1/2*wheel_mass*wheel_radius*wheel_radius}" iyz="0.0"
                     izz="${1/4*wheel_mass*wheel_radius*wheel_radius + 1/12*wheel_mass*wheel_thickness}"/>
        </inertial>
    </link>

    <joint name="left_caster_joint" type="continuous">
        <parent link="left_caster_axle_link"/>
        <child link="left_caster_link"/>
        <origin xyz="${caster_axis_offset_x} 0.0 ${-caster_axis_offset_z}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    </joint>

<!--
    <joint name="left_caster_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_caster_link"/>
        <origin xyz="${-caster_axis_x}  ${caster_wheel_base/2+wheel_thickness/2} 0.0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    </joint>
-->

    <!-- ################################Right caster Wheel##############################################-->
    <link name="right_caster_axle_link">
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0" ixy="0.0"
                     ixz="0.0"
                     iyy="0.0" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <joint name="right_caster_axle_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_caster_axle_link"/>
        <origin xyz="${-caster_axis_x} ${-caster_wheel_base/2-wheel_thickness/2} ${caster_axis_z}" rpy="0 0 0"/>
        <!-- <dynamics damping="${caster_damping}" friction="${caster_friction}"/> -->
    </joint>

    <link name="right_caster_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <origin rpy="1.5708 0 0" xyz="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <origin rpy="1.5708 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <mass value="${wheel_mass}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="${1/4*wheel_mass*wheel_radius*wheel_radius + 1/12*wheel_mass*wheel_thickness}" ixy="0.0"
                     ixz="0.0"
                     iyy="${1/2*wheel_mass*wheel_radius*wheel_radius}" iyz="0.0"
                     izz="${1/4*wheel_mass*wheel_radius*wheel_radius + 1/12*wheel_mass*wheel_thickness}"/>
        </inertial>
    </link>

    <joint name="right_caster_joint" type="continuous">
        <parent link="right_caster_axle_link"/>
        <child link="right_caster_link"/>
        <origin xyz="${caster_axis_offset_x} 0.0 ${-caster_axis_offset_z}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    </joint>

<!--
    <joint name="right_caster_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_caster_link"/>
        <origin xyz="${-caster_axis_x} ${-caster_wheel_base/2-wheel_thickness/2} 0.0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    </joint>
-->

    <!-- ################################imu##############################################-->

    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0 0 0"/>
    </joint>

    <!-- ################################chair##############################################-->

    <joint name="chair_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chair_link"/>
        <origin xyz="${chair_x} ${chair_y} ${chair_z}" rpy="0 0 0"/>
    </joint>
    <link name="chair_link">
        <collision>
            <geometry>
                <box size="${chair_thickness} ${chair_width} ${chair_height}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${chair_height/2}"/>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 ${chair_height/2}"/>
            <mass value="${chair_mass}"/>

            <inertia ixx="${1/12*chair_mass*(chair_width*chair_width + chair_height*chair_height)}" ixy="0.0" ixz="0.0"
                     iyy="${1/12*chair_mass*(chair_thickness*chair_thickness + chair_height*chair_height)}" iyz="0.0"
                     izz="${1/12*chair_mass*(chair_width*chair_width + chair_thickness*chair_thickness)}"/>
        </inertial>
    </link>
    <!-- ################################ front cam ##############################################-->
    <joint name="front_cam_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_cam_link"/>
        <origin xyz="${front_cam_x} ${front_cam_y} ${front_cam_z}" rpy="0 0 0"/>
    </joint>
    <link name="front_cam_link"/>
    <joint name="front_cam_optical_joint" type="fixed">
        <parent link="front_cam_link"/>
        <child link="front_cam_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>
    <link name="front_cam_link_optical"/>
   <!-- <sensor_d415 parent="front_cam_link" name="camera1">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </sensor_d415>-->


        <!-- ################################ right cam ##############################################-->
    <joint name="right_cam_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_cam_link"/>
        <origin xyz="${right_cam_x} ${right_cam_y} ${right_cam_z}" rpy="0 0 -1.57"/>
    </joint>
    <link name="right_cam_link"/>
    <joint name="right_cam_optical_joint" type="fixed">
        <parent link="right_cam_link"/>
        <child link="right_cam_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>
    <link name="right_cam_link_optical"/>
<!--    <sensor_d415 parent="right_cam_link" name="camera2">-->
<!--        <origin xyz="0 0 0" rpy="0 0 0"/>-->
<!--    </sensor_d415>-->

<!--  ################################ left cam ############################################## -->
    <joint name="left_cam_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_cam_link"/>
        <origin xyz="${right_cam_x} ${-right_cam_y} ${right_cam_z}" rpy="0 0 1.57"/>
    </joint>
    <link name="left_cam_link"/>
    <joint name="left_cam_optical_joint" type="fixed">
        <parent link="left_cam_link"/>
        <child link="left_cam_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>
    <link name="left_cam_link_optical"/>
<!--    <sensor_d415 parent="left_cam_link" name="camera3">-->
<!--        <origin xyz="0 0 0" rpy="0 0 0"/>-->
<!--    </sensor_d415>-->

<!-- ################################ rear cam ##############################################-->
    <joint name="rear_cam_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_cam_link"/>
        <origin xyz="${rear_cam_x} 0 ${rear_cam_z}" rpy="0 0 3.14"/>
    </joint>
    <link name="rear_cam_link"/>
    <joint name="rear_cam_optical_joint" type="fixed">
        <parent link="rear_cam_link"/>
        <child link="rear_cam_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>
    <link name="rear_cam_link_optical"/>
<!--    <sensor_d415 parent="rear_cam_link" name="camera4">-->
<!--        <origin xyz="0 0 0" rpy="0 0 0"/>-->
<!--    </sensor_d415>&ndash;&gt;-->

    <!-- ################################ rplidar ##############################################-->
    <joint name="rplidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rplidar_link"/>
        <origin xyz="${rplidar_x} ${rplidar_y} ${rplidar_z}" rpy="1.5708 0 0"/>
    </joint>
    <link name="rplidar_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <cylinder length="0.05" radius="0.025"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <cylinder length="0.05" radius="0.025"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="1e-5"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
        </inertial>
    </link>


</robot>
